export type Client = {
  id: string
  name: string
  accountId: string
  facebookPageIds?: string[]
  igUserId?: string
  type: 'paid' | 'organic'
  status: 'active' | 'closed'
  currency: string
  hasLeadGen: boolean
  cities?: string[]
  shareToken: string
}

export const CLIENTS: Client[] = [
  {
    id: 'co-kids',
    name: 'Co Kids Group',
    accountId: '248251059419736',
    facebookPageIds: ['135504167189961', '560442774095123', '1333597723368342'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: true,
    cities: ['Auckland', 'Wellington', 'Christchurch', 'Mandarin / Auckland'],
    shareToken: 'ck-x7m2p9qr4w',
  },
  {
    id: 'creative-hub',
    name: 'The Creative Hub',
    accountId: '102242766540563',
    facebookPageIds: ['200736236642517'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'ch-q4k8n3bs6t',
  },
  {
    id: 'south-sea',
    name: 'South Sea Cruises',
    accountId: '5156689774363967',
    facebookPageIds: ['111021936185'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'ss-r6w1t5jy2v',
  },
  {
    id: 'cascade',
    name: 'Cascade Creek Retreat',
    accountId: '362659505064113',
    facebookPageIds: ['437554069630323'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'cc-b8j3v7pn5m',
  },
  {
    id: 'karaka',
    name: 'DoubleTree by Hilton Auckland Karaka',
    accountId: '1842427852623651',
    facebookPageIds: ['104961075212031'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'ka-y2l9f4dh8c',
  },
  {
    id: 'pocket-bar',
    name: 'Pocket Bar',
    accountId: '1695711684136476',
    facebookPageIds: ['539469452885415'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'pb-d5s8m1zk3e',
  },
  {
    id: 'hilton-nz',
    name: 'Hilton New Zealand',
    accountId: '250039821854564',
    facebookPageIds: ['170839166261244'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'hnz-e3g6c9uw7a',
  },
  {
    id: 'hilton-fiji',
    name: 'Hilton Fiji Beach Resort and Spa',
    accountId: '647548016018133',
    facebookPageIds: ['52013960754'],
    type: 'paid',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'hfj-u7a4h2xq1f',
  },
  {
    id: 'mai-sunset',
    name: 'Mai Sunset Beach Resort',
    accountId: '',
    facebookPageIds: ['996924450165919'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'ms-w9n5k6rb4g',
  },
  // ── Organic-only clients ──────────────────────────────────────────────────
  {
    id: 'blue-lagoon',
    name: 'Blue Lagoon Cruises',
    accountId: '',
    facebookPageIds: ['75421254639'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'blc-k3n7p2qx9m',
  },
  {
    id: 'south-sea-island',
    name: 'South Sea Island',
    accountId: '',
    facebookPageIds: ['190230148201358'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'ssi-m8v4w1jh6r',
  },
  {
    id: 'south-sea-cats',
    name: 'South Sea Cats',
    accountId: '',
    facebookPageIds: ['359277120605823'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'ssc-f2t6b9yl4z',
  },
  {
    id: 'south-sea-sailing',
    name: 'South Sea Sailing',
    accountId: '',
    facebookPageIds: ['2193066607444805'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'sss-q5c8n3xk7d',
  },
  {
    id: 'yasawa-adventures',
    name: 'Yasawa Adventures Fiji',
    accountId: '',
    facebookPageIds: ['330487090305827'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'yaf-r1h7m4wz2s',
  },
  {
    id: 'malamala',
    name: 'Malamala Beach Club Fiji',
    accountId: '',
    facebookPageIds: ['1842453489303121'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'mbc-e9j3v6pk1n',
  },
  {
    id: 'bistro-lago',
    name: 'Bistro Lago',
    accountId: '',
    facebookPageIds: ['117670061642922'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'bl-u4x8c2ft5w',
  },
  {
    id: 'hilton-taupo',
    name: 'Hilton Lake Taupo',
    accountId: '',
    facebookPageIds: ['139446452782133'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'hlt-a7g3s9qr6b',
  },
  {
    id: 'bledisloe',
    name: 'Bledisloe Holiday Park',
    accountId: '',
    facebookPageIds: ['574571809065993'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'bhp-z2d5n8mv3k',
  },
  {
    id: 'tussock-cafe',
    name: 'Tussock Cafe Wellington',
    accountId: '',
    facebookPageIds: ['101906665819933'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'tcw-y6f1j4xh8p',
  },
  {
    id: 'osteria-group',
    name: 'Osteria Group',
    accountId: '',
    facebookPageIds: ['103418121250094'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'og-w3b7t5nc9e',
  },
  {
    id: 'bianca-ray',
    name: 'Bianca Ray Jewellery',
    accountId: '',
    facebookPageIds: ['126295383909024'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'brj-k9s2v6hz4q',
  },
  {
    id: 'bellini',
    name: 'Bellini',
    accountId: '',
    facebookPageIds: ['139419953245786'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'bel-p5m1w8jy7r',
  },
  {
    id: 'fish-restaurant',
    name: 'FISH',
    accountId: '',
    facebookPageIds: ['154390951342281'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'fsh-c8n4k2xb6t',
  },
  {
    id: 'massey-venues',
    name: 'Massey Venues',
    accountId: '',
    facebookPageIds: ['106419555016500'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'mv-d1q7g3ps5f',
  },
  {
    id: 'odi-nutrition',
    name: 'Odi Nutrition',
    accountId: '',
    facebookPageIds: ['106221351721486'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'odn-h4v9e6mr2w',
  },
  {
    id: 'ian-morgan',
    name: 'Ian Morgan Property Brokers Waikato Rural',
    accountId: '',
    facebookPageIds: ['483950028362346'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'impb-j6t3c8nk1x',
  },
  {
    id: 'lucidkiwi',
    name: 'Lucidkiwi',
    accountId: '',
    facebookPageIds: ['744678289009860'],
    type: 'organic',
    status: 'active',
    currency: 'NZD',
    hasLeadGen: false,
    shareToken: 'lk-s5r2y9wf7v',
  },
]

export function getClient(id: string): Client | undefined {
  return CLIENTS.find((c) => c.id === id)
}

export function getClientByToken(token: string): Client | undefined {
  return CLIENTS.find((c) => c.shareToken === token)
}

export const paidClients = CLIENTS.filter((c) => c.type === 'paid' && c.status === 'active')
export const organicClients = CLIENTS.filter((c) => c.type === 'organic' && c.status === 'active')
